name: Ping URL
description: Pings a URL until maximum trials have exceeded. If result is not 200, fails.

inputs:
  url:
    description: URL to ping
    required: true
    default: https://www.google.com
  delay:
    description: Time in seconds to wait between trials
    required: false
    default: 5
  max_trials:
    description: maximum number of trials
    default: 5
    required: false
  
runs:
  using: docker
  image: Dockerfile

outputs:
  website-reachable:
    description: Boolean to indicate if the website was reachable or not.