name: 02-workflow-events
on:
  workflow_dispatch:

jobs:
  event_name:
    runs-on: ubuntu-latest
    steps:
      - name: Event Name
        run: | 
          echo "Event Name: ${{ github.event_name }}"