name: 05 - 1 - Event Filters and Activity Types

on:
    workflow_dispatch:
    pull_request: 
        types: [opened, synchronize]
        branches: 
            - master

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: echo  
              run : echo "Running whenever a PR is opened or synchronized AND base branch is main"