name: 05 - 2 - Event Filters and Activity Types
on:
    workflow_dispatch: 
    pull_request: 
        types: [closed]
        branches: 
            - master

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "Running whenever a PR is closed" 