name: 06 - Contexts
on:
    push:
    workflow_dispatch:  

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'overwritten-1'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'overwritten-2'
        steps:
            - name: Display Information
              run: | 
                echo "Event Name : ${{github.event_name}}"
                echo "Ref : ${{github.ref}}"
                echo "SHA : ${{github.sha}}"
                echo "Actor : ${{github.actor}}"
                echo "Workflow : ${{github.workflow}}"
                echo "Run ID : ${{github.run_id}}"
                echo "Run Number : ${{github.run_number}}"
            - name: Retrieve Variable
              run: |
                echo "MY var : ${{ vars.MY_VAR }}" 
                echo "MY var : ${{ secrets.MY_VAR }}" 
            - name: ENV Variable
              run: |
                echo "MY_WORKFLOW_VAR : ${{ env.MY_WORKFLOW_VAR }}" 
                echo "MY_OVERWRITTEN_VAR : ${{ env.MY_OVERWRITTEN_VAR }}" 
                echo "MY_JOB_VAR : ${{ env.MY_JOB_VAR }}"
