name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build_status:
                type: choice
                default: success
                options:
                    - success
                    - failure

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.status}}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo $GITHUB_OUTPUT
            - name: BUILD
              id: build
              run: echo status=${{inputs.build_status}} >> $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{success()}}
        steps:
            - name: Deploy
              run: echo "Deploying ${{needs.build.outputs.build-status}}"
