name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        default: true
        type: boolean
        description: Execute Cache Step?
      node-version:
        default: 22.x
        type: choice
        options:
          - 18.x
          - 20.x
          - 22.x

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    outputs:
      deps-cache-key: ${{ steps.cache_key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}

      - name: Calculate cache key
        id: cache_key
        run: echo CACHE_KEY=deps-node-modules-${{ hashFiles('react-app/package-lock.json') }} >> $GITHUB_OUTPUT

      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache}}
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache_key.outputs.CACHE_KEY}}
          path: react-app/node_modules

      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
  linting:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}

      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache}}
        uses: actions/cache@v3
        with:
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
          path: react-app/node_modules

      - name: Testing
        run: echo "Testing"

      - name: Linting
        run: echo "Linting"
  build:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
          path: react-app/node_modules

      - name: Testing
        run: echo "Testing"

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
