name: 14 - Working with artifacts

on: 
    workflow_dispatch:

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: react-app
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 20.x
        
        - name: Download cached dependencies
          id: cache
          uses: actions/cache@v3
          with:
            key: deps-node-module-${{hashFiles('react-app/package-lock.json')}}
            path: react-app/node_modules
        
        - name: Install Dependencies
          if: ${{steps.cache.outputs.cache-hit != 'true'}}
          run: npm ci
        
        - name: Unit Tests
          run: echo 'Testing'
        
        - name: Build Code
          run: npm run build
        
        - name: Upload build files
          uses: actions/upload-artifact@v4
          with:
            name: app
            path: react-app/dist
    
    deploy:
        runs-on: ubuntu-latest
        needs:
            - test-build
        steps:
          - name: Download build files
            uses: actions/download-artifact@v4
            with:
                name: app
                path: dist