name: 15 - Working with Matrices

on:
    workflow_dispatch: 

jobs:
    include-example:
        runs-on: ubuntu-latest
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}
        strategy:
          matrix:
            color: [red, green]
            shape: [circle, square]
            size: [small, large]
            include:
              - color: red
                opacity: 75
              - shape: circle
                opacity: 100
              - color: red
                shape: triangle
              - opacity: 50
              - color: green
                shape: circle
                size: medium
            exclude:
              - color: green
              - shape: circle
            
        steps:
          - name: Dummy step
            run: echo "${{matrix.color}}-${{matrix.shape}}=${{matrix.size}}-${{matrix.opacity}}"