name: 16 - Working with Environments
on:
    workflow_dispatch:

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Deploying to staging
              run: | 
                echo "Deploying to staging"

    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - name: E2E tests
              run: echo "Running E2E"
    
    deploy-prod:
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
        environment: prod
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: echo
              run : echo "Deploying to prod"

              