name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options:
                    - dev
                    - prod
                required: true

env:
    working-directory: react-app

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
  
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              id: setup-node
              with:
                node-version: 20.x
                working-directory: ${{env.working-directory}}
                target-env: ${{inputs.target-env}}
            
            - name: Print Outputs
              run: |
                echo "Installed dependencies: ${{ steps.setup-node.outputs.installed-deps }}"
                echo "Random Output: ${{ steps.setup-node.outputs.random-output }}"

            - name: Test
              run: npm run test
            
            - name: Build
              run: npm run build
