name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | BB- ${{inputs.base-branch}} | TG- ${{inputs.target-branch}} | WD - ${{inputs.working-directory}}

on:
    workflow_dispatch:
      inputs:
        base-branch:
          type: string
          default: master
        target-branch:
          type: string
          default: update-dependencies
        working-directory:
          type: string
          default: react-app

permissions:
  contents: write
  pull-requests: write

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
              with:
                base-branch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.target-branch }}
                working-directory: ${{ inputs.working-directory }}
                gh-token: ${{ secrets.GITHUB_TOKEN }}
              
            
            