name: 17 - 3 - Custom Actions - Docker

on:
    workflow_dispatch:
      inputs:
        url:
          type: string
          required: true
        delay:
          description: Time in seconds to wait between trials
          required: false
          default: '5'
        max_trials:
          description: maximum number of trials
          default: '5'
          required: false

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Pings URL
              uses: ./.github/actions/docker-ping-url
              id: ping-url
              with:
                url: ${{inputs.url}}
                delay: ${{inputs.delay}}
                max_trails: ${{inputs.max_trials}}
            
            - name: Print Custom URL
              run: |
                echo "Website Reachable: ${{ steps.ping-url.outputs.website-reachable }}"
